---
title: "Homework 4"
format: html
---

Question 1
```{r}
# Assigning to n_dims a single random integer between 3 and 10
n_dims <- sample(3:10, size = 1)
print(n_dims)

# Create a vector of consecutive integers from 1 to n_dims^2
my_vec <- seq(from = 1, to = n_dims^2)

print(my_vec)

# Using the sample function to randomly reshuffle the values
my_shuffle <- sample(x= my_vec, size = length(my_vec))

print(my_shuffle)

# Create a square matrix using the shuffled values
my_mat <- matrix(data = my_shuffle,
                    nrow =sqrt(length(my_shuffle)))

# print the matrix
print(my_mat)


# Transposing matrix
transposed_matrix <- t(my_mat)
print(transposed_matrix)

# calculate the sum of the element in the first row
sum(transposed_matrix[1,])

#c calculate the mean of the elements in the first row

mean(transposed_matrix[1,])

#calculate the sum and the mean of the elements in the first row and then the last row

sum(transposed_matrix[sqrt(length(transposed_matrix)),])

mean(transposed_matrix[sqrt(length(transposed_matrix)),])


#assigning and using the eigen function
eigen_result <- eigen(transposed_matrix)

typeof(eigen_result$values)

# Eigenvectors
typeof(eigen_result$vectors)

```


Question 2
```{r}
 # Creating a list with the following named elements
   # 4 X 4 matrix filled with random uniform values
 my_mat <- matrix(runif(16), nrow =4)

my_logical <- sample(1:100, size= 100) > 50

lower_case <- sample(letters, size =26)

# Creating a new list, which has the element[2,2] from the matrix, the second element of the logical vector, and the second element of the letters vector
new_list <- list(my=my_mat[2,2], logic=my_logical[2], lower=lower_case[2])
typeof(new_list$my)

typeof(new_list$logic)
typeof(new_list$lower)

# combine the underlying elements from the new list into a single atomic vector with the c() function
new_vec <- c(new_list$my, new_list$logic, new_list$lower)
typeof(new_vec)


```


QUestion 3
```{r}
#Create a data frame with the two variables (= columns) and 26 cases (= rows) below
 df <- data.frame(
    # we are calling the first variable my _unis and fill it with 26 random uniform values from 0 to 10
    my_unis = runif(26, min =0, max = 10),
    #call the second variable my_letters and fill it with 26 capitalletters in random order
    my_letters = sample(letters, 26)
    
 )

 # for the first variable, use a single line of code in R to select 4

 # m[1,1] <- NA
 # m[5,4] <- NA

 df[sample(1:26, size =4), 1] <-  NA

 # for the first variable, write a single line of Rcode to identify which rows have the missing values
 which(!complete.cases(df))

 # re-order the entire data frame to arrange the second variable in alphabetical order
df <- data.frame(df[,1], sort(df[,2]))

# calculate the column mean for the first variable
mean(df[,1], na.rm = T)



```